spring.application.name=sfmovies-api
server.port=8081

movie.api.url=https://data.sfgov.org/resource/yitu-d5am.json

#cache
spring.cache.type=caffeine
spring.cache.caffeine.cache-names=allMovies
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=10m
